### ISSUE TITLE
支持单独配置终端日志级别

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-common-tools#134]
sofa-common-tools 目前支持把 logger 的日志输出到文件的同时在 console 输出，但是目前的 level 是一样的，有时候 console 需要不同的日志级别，希望能够提供这个能力。

![image](https://user-images.githubusercontent.com/8054939/111972319-4ced9480-8b38-11eb-8690-bb90eb326ebb.png)

可能的做法：
1. One may consider appender filer.
2. `AppenderControl` is also applicable in log4j2.

**Comment by alaneuler** [comment]
AppenderControl is also applicable.

**Comment by dkisser** [comment]
认领

**Comment by alaneuler** [comment]
@dkisser 已经 assign 给你了～

**Comment by dkisser** [comment]
> @dkisser 已经 assign 给你了～

收到
