### ISSUE TITLE
About Loglevel dynamic configuration implementation

### ISSUE THREAD

**Issue by imsunv** [sofastack/sofa-common-tools#50]
该组件提供了修改日志级别的接口，我们准备对接自己的配置中心实现日志等级的动态配置，想咨询下你们是如何使用该组件实现的，未来是否会提供类似的功能比如对接一些配置中心比如zookeeper或者 Apollo Nacos 等

**Comment by QilongZhang** [comment]
sofa-common-tools 没有对接配置中心动态推送日志级别，目前暂时无计划支持。如果有兴趣，欢迎提供方案和PR.
